// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/gofiber/fiber/v2"
	"github.com/google/wire"
	"github.com/pplmx/blog-go/internal"
	"github.com/pplmx/blog-go/internal/controller"
	"github.com/pplmx/blog-go/internal/db"
	"github.com/pplmx/blog-go/internal/repository"
	"github.com/pplmx/blog-go/internal/service"
)

// Injectors from wire.go:

func NewApp() *fiber.App {
	app := internal.NewFiberApp()
	return app
}

// wire.go:

var repositoryProviderSet = wire.NewSet(db.NewDBConn, repository.NewPostRepository)

var serviceProviderSet = wire.NewSet(service.NewPostService)

var controllerProviderSet = wire.NewSet(controller.NewPostController)

var providerSet = wire.NewSet(internal.NewFiberApp, repositoryProviderSet,
	serviceProviderSet,
	controllerProviderSet,
)
