name: CD # Continuous Deployment

on:
    push:
        # e.g. 1.0.0, v2.0.0, v0.1.0, v0.2.0-alpha, v0.3.0+build-71edf32
        tags:
            - '[v]?[0-9]+\.[0-9]+\.[0-9]+.*'

jobs:
    todo:
        name: TODO
        runs-on: ubuntu-latest
